version: "3.5"

services:
  api01: &api
    image: cristovaoolegario/rinha-de-backend-2024-q1:latest
    hostname: api01
    restart: always
    networks: [default]
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/rinha
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    networks: [default]
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U test -d rinha'"]
      interval: 3s
      timeout: 60s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-network
